### ISSUE TITLE
Hi Cheerpipe

### ISSUE THREAD

**Issue by ngidwani123** [Cheerpipe/RGBFusion390SetColor#1]
Cheerpipe can you help me on how to use your tool. I downloaded your exe to rgb fusion location but i dont know how to use command line. Can you explain how and where I type --areas and the other commands. Thank you.

**Comment by Cheerpipe** [comment]
Sure, my English is not so good but should be enough.

--areas will show you your areas. 

An area is a led zone or led array on your main board or any other rgbfusion device.

Each area is uniquely identified with a number.

It is important to note that area -1 represent all areas.


To change an area you must use --setarea command with the following parameters.

--setarea:area_id:mode:r:g:b

This example set all areas to red:

--setarea:-1:0:255:0:0

Mode 0 is still, 1 is breath......

Pls tell me back  if my instructions are helpful to you.

**Comment by ngidwani123** [comment]
Where do I write "--areas"

**Comment by ngidwani123** [comment]
Can you help me, where do put int the commands

**Comment by ngidwani123** [comment]
donde escribo "--areas"

**Comment by Cheerpipe** [comment]
Create a Shortcut, create a .bat file or run it directly from Run dialog (Win+R)
![Screenshot](https://user-images.githubusercontent.com/972765/67529659-23a2ad80-f693-11e9-947d-5d56789db616.jpg)

![Screenshot2](https://user-images.githubusercontent.com/972765/67529715-551b7900-f693-11e9-892a-9a519792a9e9.jpg)
