### ISSUE TITLE
Wrote data via i2c to my motherboard, any chance you could help?

### ISSUE THREAD

**Issue by plantroon** [Cheerpipe/RGBFusion390SetColor#2]
I accidentally wrote data via i2c to the motherboard. My USB controller is misbehaving, RGB stopped working and BIOS re-flashing didn't fix it. Is there a way to reset these registers available over i2c or could someone with Z390 Aorus Pro and Linux please run these commands on their system (as root/with sudo):

First install i2c-tools in your distro (apt-get i2c-tools). Then run:

modprobe i2c-dev
i2cdump -y 0 0x68

And grab the output.

This may not help me at all though. If you have any other idea maybe? Is there a way to "reset" the controller?

**Comment by Cheerpipe** [comment]
Try this at your own risk.

[ITESHFU_v3.1.1.zip](https://github.com/Cheerpipe/RGBFusion390SetColor/files/4441704/ITESHFU_v3.1.1.zip)

**Comment by plantroon** [comment]
Thanks, sadly, I RMA'd the board already. So I cannot test it and will not test on the new board as I really can't afford any more time without the computer, especially in these days.

Did you dump the correct data from somewhere?
