### ISSUE TITLE
RGB Fusion version

### ISSUE THREAD

**Issue by JonathanSamelson** [Cheerpipe/RGBFusion390SetColor#3]
Hi Cheerpie and thanks for your contribution.

**Describe the bug**
I can't start the app, nothing happens when I execute RGBFusion390SetColor.exe --areas in a command prompt (as admin) or with any other method. I can see a short load after the execution and the nothing. 
**Which RGB Fusion version do you use ? Actually I use the version 18.1019 that I found on the web because I have a BSOD issue with version 2.0. Could it be related ?** 
I checked, I have the LedLib2.dll and SelLEDControl.dll in the folder.

**To Reproduce**
1. Move RGBFusion390Sender.dll and RGBFusion390SetColor.exe to the RGB Fusion installation folder.
2. Start a command prompt or a powershell as administrator
3. Write "C:\Program Files (x86)\GIGABYTE\RGBFusion\RGBFusion390SetColor.exe" --areas
4. No output, no window appears, the prompt is ready to get the next command.

**Expected behavior**
The program starts and shows the available areas.

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1909
 - Mother board: Aorus Z390 Pro 

Hope you can help me and many thanks in advance!

**Comment by JonathanSamelson** [comment]
Hi @Cheerpipe 

I don't know if it can help but I installed the requirements to make it work with Aurora. When Aurora is opened I can get the following error when I execute command lines. 

![RGBFusion390SetColor-Bug](https://user-images.githubusercontent.com/19322574/77249031-9dd55f00-6c3e-11ea-8165-3ca434adcdce.png)

**Comment by JonathanSamelson** [comment]
Eventually, I managed to make it work! I changed the version of RGB Fusion to B19.0919.1

For other person that may have the same issue, this version can be found here: https://www.touslesdrivers.com/index.php?v_page=23&v_code=62684

**Comment by stottpie** [comment]
I'm very interested in how this turns out.  I'm at my wits end with finding a good version because I was getting so many blue screens with rgbfusion2.0.  Tried this command line and same result, it executed but nothing happens.  Thanks

**Comment by JonathanSamelson** [comment]
I advice you to find the most recent version that don't get you blue screens. The version  B19.0919.1 is already called "RGB Fusion 2.0" and it was released around the same period as this project.

I also read that changing the bios version can help to find a good version, depending on your mother board... But that's surely more annoying as trial and error.

**Comment by stottpie** [comment]
Thanks, that version worked.  We'll see if it blue screens on me..
