### ISSUE TITLE
What restricts speed?

### ISSUE THREAD

**Issue by CaelTheQuail** [Cheerpipe/RGBFusion390SetColor#5]
Hello,

I'm just wondering what part of the project restricts the speed to a max of 15 commands per second. And if it is possible to make it any faster?

Thanks

**Comment by Cheerpipe** [comment]
The rgbfusion itself. When you have more than just a motherboard (I also have rams and vga working with rgbfusion) rgbfusion components takes a lot of time (almost 100ms) to apply changes. If you only have the motherboard your framerste will be a lot higher.

**Comment by CaelTheQuail** [comment]
Thanks,

I don't know much about programming in C and was wondering how I would use the named pipe?

**Comment by Cheerpipe** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-use-named-pipes-for-network-interprocess-communication

Use the naped pipe just the same way you use command line parameters:

Example of cliente: https://github.com/Cheerpipe/RGBFusion390SetColor/tree/master/RGBFusion390Sender

Example of use: https://github.com/Cheerpipe/RGBFusion390SetColor/blob/master/Aurora/Scripts/Devices/RgbFusionMB_VGA_native.cs
